name: CI Testing 3

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run -w packages/backend/ lint
      - run: npm run -w packages/frontend lint
      - run: npm run -w package/frontend build
